<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    style="margin: auto; background: rgba(255, 255, 255, 0); display: block; shape-rendering: auto;"
    width="42px"
    height="42px"
    viewBox="0 0 100 100"
    preserveAspectRatio="xMidYMid"
  >
    <circle
      cx="50"
      cy="28"
      r="18"
      fill="#ff793f"
    >
      <animate
        attributeName="cy"
        dur="1s"
        repeatCount="indefinite"
        calcMode="spline"
        keySplines="0.45 0 0.9 0.55;0 0.45 0.55 0.9"
        keyTimes="0;0.5;1"
        values="28;72;28"
      />
    </circle>
    <!-- [ldio] generated by https://loading.io/ --></svg>
</template>
